import type { Metadata } from "next";
import Link from "next/link";
import LegalLayout, { LegalSection } from "@/components/LegalLayout";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description: "The terms that govern your use of LikhoAI.",
};

const LAST_UPDATED = "18 July 2026"; // TODO: keep this in sync when you actually change the terms

export default function TermsPage() {
  return (
    <LegalLayout title="Terms & Conditions" updated={LAST_UPDATED}>
      <LegalSection title="1. Acceptance of Terms">
        <p>
          By accessing or using LikhoAI, you agree to be bound by these Terms & Conditions. If
          you don&apos;t agree, please don&apos;t use the service.
        </p>
      </LegalSection>

      <LegalSection title="2. Description of Service">
        <p>
          LikhoAI generates social media captions, hashtags, and content ideas in English, Urdu
          script, and Roman Urdu, using AI, based on the information you provide. It&apos;s a
          writing aid intended to save you time — not a substitute for your own judgment about
          what to post.
        </p>
      </LegalSection>

      <LegalSection title="3. Account Registration">
        <p>
          Some features (saving history, favorites) require an account. You&apos;re responsible
          for keeping your login credentials secure and for all activity under your account.
        </p>
      </LegalSection>

      <LegalSection title="4. Acceptable Use">
        <p>You agree not to use LikhoAI to:</p>
        <ul className="list-disc space-y-1.5 pl-5">
          <li>Generate content that is illegal, hateful, defamatory, or misleading.</li>
          <li>Attempt to disrupt, reverse-engineer, or abuse the service or its underlying AI.</li>
          <li>Impersonate another person or business without authorization.</li>
        </ul>
      </LegalSection>

      <LegalSection title="5. AI-Generated Content Disclaimer">
        <p>
          Captions, hashtags, and ideas are generated by AI and may occasionally contain
          inaccurate, outdated, or inappropriate wording. LikhoAI does not verify facts, prices,
          dates, or claims included in generated content.{" "}
          <span className="font-semibold text-ink">
            You are responsible for reviewing and editing generated content before posting it.
          </span>
        </p>
      </LegalSection>

      <LegalSection title="6. Ownership of Generated Content">
        <p>
          You own the rights to the captions and content you generate and choose to use for your
          business. Because content is AI-generated, we can&apos;t guarantee that any specific
          caption is unique or hasn&apos;t been produced for another user with similar inputs.
        </p>
      </LegalSection>

      <LegalSection title="7. Subscription & Payments">
        <p>
          LikhoAI offers a free tier with a limited number of generations per day. Paid plans
          remove that limit and add extra features, as described on our Pricing page. Paid plans
          are billed on a recurring basis until cancelled; you can cancel anytime, and access
          continues until the end of the current billing period.
        </p>
      </LegalSection>

      <LegalSection title="8. Third-Party Services">
        <p>
          LikhoAI relies on Google&apos;s Gemini API to generate content. Availability, quality,
          and behavior of generated content may be affected by changes to that underlying
          service, which are outside our control.
        </p>
      </LegalSection>

      <LegalSection title="9. Limitation of Liability">
        <p>
          LikhoAI is provided &quot;as is,&quot; without warranties of any kind. To the fullest
          extent permitted by law, we are not liable for any indirect, incidental, or
          consequential damages arising from your use of the service, including losses related
          to content you posted based on AI-generated output.
        </p>
      </LegalSection>

      <LegalSection title="10. Termination">
        <p>
          We may suspend or terminate accounts that violate these Terms. You may stop using
          LikhoAI and delete your account at any time.
        </p>
      </LegalSection>

      <LegalSection title="11. Changes to These Terms">
        <p>
          We may update these Terms occasionally. Continued use of LikhoAI after changes means
          you accept the updated Terms.
        </p>
      </LegalSection>

      <LegalSection title="12. Governing Law">
        <p>These Terms are governed by the laws of Pakistan.</p>
      </LegalSection>

      <LegalSection title="13. Contact Us">
        <p>
          Questions about these Terms? Reach out via our{" "}
          <Link href="/contact" className="font-semibold text-brand-600 hover:text-brand-700">
            Contact page
          </Link>
          .
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
